services:
  - type: web
    name: smart-expense-manager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn expense_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
